/**
 * Agent file template — Step 12
 *
 * This is a string template used by the `create_agent` meta-tool.
 * Placeholders are replaced before the file is written to disk:
 *
 *   __NAME__         → agent ID / filename stem  (e.g. "my-agent")
 *   __DESCRIPTION__  → one-line description
 *   __INSTRUCTIONS__ → full system prompt (may be multi-line, escaped)
 *   __MODEL__        → model ID string, or the caller's default
 *
 * The generated file:
 *   - Has a default export that is a Mastra Agent instance
 *   - Can be imported by the registry without further compilation (tsx)
 *   - Follows the same shape the registry's type guard checks
 */

/**
 * Returns the source code for a new agent extension file.
 *
 * @param name         - Agent identifier (used as the `id` field)
 * @param description  - Short description shown in the registry summary
 * @param instructions - Full system prompt for the agent
 * @param modelId      - Model to use (defaults to the harness default if empty)
 */
export function renderAgentTemplate(
  name: string,
  description: string,
  instructions: string,
  modelId: string,
): string {
  // Escape backticks inside the instructions string so template literals survive
  const escapedInstructions = instructions.replace(/`/g, '\\`').replace(/\${/g, '\\${');

  return `/**
 * Extension agent: ${name}
 * ${description}
 *
 * Auto-generated by /create_environment.
 * Edit this file freely — changes are picked up after reload_ecosystem.
 */

import { Agent } from '@mastra/core/agent';

const agent = new Agent({
  id: '${name}',
  name: '${name}',
  model: '${modelId}',
  instructions: \`${escapedInstructions}\`,
});

export default agent;
`;
}
