/**
 * Tool file template
 *
 * String template used by the `create_tool` meta-tool.
 *
 * The `inputSchema` parameter is a full `z.object(...)` expression — the agent
 * writes the complete schema, not just the fields inside it. This prevents the
 * common mistake of wrapping an already-complete schema in another z.object().
 *
 * The generated file:
 *   - Default-exports a Mastra Tool (createTool result)
 *   - Named-exports `category` so the registry knows which permission bucket it belongs to
 *   - Is importable by tsx without a separate build step
 */

/**
 * Returns the
 * source code for a new tool extension file.
 *
 * @param name           - Tool identifier (used as the `id` field)
 * @param description    - Short description shown in registry and tool approval prompts
 * @param inputSchema    - Full z.object() expression, e.g. `z.object({ url: z.string() })`
 * @param implementation - Async function body; access inputs via inputData.fieldName
 * @param category       - Permission category controlling approval policy
 */
export function renderToolTemplate(
  name: string,
  description: string,
  inputSchema: string,
  implementation: string,
  category: 'read' | 'edit' | 'execute' | 'mcp' | 'other',
): string {
  const escapedDescription = description.replace(/`/g, '\\`');

  return `/**
 * Extension tool: ${name}
 * ${description}
 *
 * Auto-generated by /create_environment.
 * Edit this file freely — changes are picked up after reload_ecosystem.
 */

import { createTool } from '@mastra/core/tools';
import { z } from 'zod/v4';

export const category = '${category}' as const;

const tool = createTool({
  id: '${name}',
  description: \`${escapedDescription}\`,
  inputSchema: ${inputSchema},
  execute: async (inputData) => {
    ${implementation}
  },
});

export default tool;
`;
}
